// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AhliWaris struct {
	ID           int64          `json:"id"`
	BerkasID     int64          `json:"berkas_id"`
	Nama         string         `json:"nama"`
	Nik          string         `json:"nik"`
	Umur         sql.NullInt64  `json:"umur"`
	JenisKelamin sql.NullString `json:"jenis_kelamin"`
	Agama        sql.NullString `json:"agama"`
	Alamat       sql.NullString `json:"alamat"`
	Keterangan   sql.NullString `json:"keterangan"`
}

type BerkasWaris struct {
	ID                       int64         `json:"id"`
	NomorSurat               string        `json:"nomor_surat"`
	Tahun                    int64         `json:"tahun"`
	Urutan                   int64         `json:"urutan"`
	Tanggal                  string        `json:"tanggal"`
	TempatTinggalPewaris     string        `json:"tempat_tinggal_pewaris"`
	PenerimaKuasaAhliWarisID sql.NullInt64 `json:"penerima_kuasa_ahli_waris_id"`
	Status                   string        `json:"status"`
	CreatedBy                sql.NullInt64 `json:"created_by"`
	CreatedAt                string        `json:"created_at"`
	UpdatedAt                string        `json:"updated_at"`
}

type Harta struct {
	ID        int64  `json:"id"`
	BerkasID  int64  `json:"berkas_id"`
	Deskripsi string `json:"deskripsi"`
}

type NomorAwal struct {
	Tahun      int64 `json:"tahun"`
	UrutanAwal int64 `json:"urutan_awal"`
}

type Pejabat struct {
	ID        int64  `json:"id"`
	Jabatan   string `json:"jabatan"`
	Nama      string `json:"nama"`
	Nip       string `json:"nip"`
	Aktif     int64  `json:"aktif"`
	CreatedAt string `json:"created_at"`
}

type Pengaturan struct {
	ID            int64          `json:"id"`
	NamaKelurahan sql.NullString `json:"nama_kelurahan"`
	Kecamatan     sql.NullString `json:"kecamatan"`
	Kabupaten     sql.NullString `json:"kabupaten"`
	Provinsi      sql.NullString `json:"provinsi"`
	FormatNomor   sql.NullString `json:"format_nomor"`
}

type Pewaris struct {
	ID               int64  `json:"id"`
	BerkasID         int64  `json:"berkas_id"`
	Nama             string `json:"nama"`
	Nik              string `json:"nik"`
	TglMeninggal     string `json:"tgl_meninggal"`
	NoSuratKematian  string `json:"no_surat_kematian"`
	TglSuratKematian string `json:"tgl_surat_kematian"`
}

type Saksi struct {
	ID       int64          `json:"id"`
	BerkasID int64          `json:"berkas_id"`
	Nama     string         `json:"nama"`
	Ttl      sql.NullString `json:"ttl"`
	Alamat   sql.NullString `json:"alamat"`
	Nik      sql.NullString `json:"nik"`
	Hubungan sql.NullString `json:"hubungan"`
}

type User struct {
	ID                 int64  `json:"id"`
	Username           string `json:"username"`
	PasswordHash       string `json:"password_hash"`
	Nama               string `json:"nama"`
	Role               string `json:"role"`
	MustChangePassword int64  `json:"must_change_password"`
	CreatedAt          string `json:"created_at"`
}
