// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countPewarisByNik = `-- name: CountPewarisByNik :one
SELECT COUNT(*) FROM pewaris WHERE nik = ?
`

// PEWARIS
func (q *Queries) CountPewarisByNik(ctx context.Context, nik string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPewarisByNik, nik)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAhliWaris = `-- name: CreateAhliWaris :one
INSERT INTO ahli_waris (berkas_id, urutan, nama, nik, umur, jenis_kelamin, agama, alamat, keterangan, tempat_lahir, tgl_lahir, pekerjaan)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, berkas_id, urutan, nama, nik, umur, jenis_kelamin, agama, alamat, keterangan, tempat_lahir, tgl_lahir, pekerjaan
`

type CreateAhliWarisParams struct {
	BerkasID     int64          `json:"berkas_id"`
	Urutan       int64          `json:"urutan"`
	Nama         string         `json:"nama"`
	Nik          string         `json:"nik"`
	Umur         sql.NullInt64  `json:"umur"`
	JenisKelamin sql.NullString `json:"jenis_kelamin"`
	Agama        sql.NullString `json:"agama"`
	Alamat       sql.NullString `json:"alamat"`
	Keterangan   sql.NullString `json:"keterangan"`
	TempatLahir  sql.NullString `json:"tempat_lahir"`
	TglLahir     sql.NullString `json:"tgl_lahir"`
	Pekerjaan    sql.NullString `json:"pekerjaan"`
}

// AHLI WARIS
func (q *Queries) CreateAhliWaris(ctx context.Context, arg CreateAhliWarisParams) (AhliWaris, error) {
	row := q.db.QueryRowContext(ctx, createAhliWaris,
		arg.BerkasID,
		arg.Urutan,
		arg.Nama,
		arg.Nik,
		arg.Umur,
		arg.JenisKelamin,
		arg.Agama,
		arg.Alamat,
		arg.Keterangan,
		arg.TempatLahir,
		arg.TglLahir,
		arg.Pekerjaan,
	)
	var i AhliWaris
	err := row.Scan(
		&i.ID,
		&i.BerkasID,
		&i.Urutan,
		&i.Nama,
		&i.Nik,
		&i.Umur,
		&i.JenisKelamin,
		&i.Agama,
		&i.Alamat,
		&i.Keterangan,
		&i.TempatLahir,
		&i.TglLahir,
		&i.Pekerjaan,
	)
	return i, err
}

const createBerkas = `-- name: CreateBerkas :one
INSERT INTO berkas_waris (tahun, urutan, reg_no_camat, reg_no_lurah, tanggal_surat, tempat_tinggal_pewaris, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, tahun, urutan, reg_no_camat, reg_no_lurah, tanggal_reg_camat, tanggal_reg_lurah,
          tanggal_surat, tempat_tinggal_pewaris, penerima_kuasa_ahli_waris_id, status,
          created_by, created_at, updated_at
`

type CreateBerkasParams struct {
	Tahun                int64         `json:"tahun"`
	Urutan               int64         `json:"urutan"`
	RegNoCamat           string        `json:"reg_no_camat"`
	RegNoLurah           string        `json:"reg_no_lurah"`
	TanggalSurat         string        `json:"tanggal_surat"`
	TempatTinggalPewaris string        `json:"tempat_tinggal_pewaris"`
	CreatedBy            sql.NullInt64 `json:"created_by"`
}

func (q *Queries) CreateBerkas(ctx context.Context, arg CreateBerkasParams) (BerkasWaris, error) {
	row := q.db.QueryRowContext(ctx, createBerkas,
		arg.Tahun,
		arg.Urutan,
		arg.RegNoCamat,
		arg.RegNoLurah,
		arg.TanggalSurat,
		arg.TempatTinggalPewaris,
		arg.CreatedBy,
	)
	var i BerkasWaris
	err := row.Scan(
		&i.ID,
		&i.Tahun,
		&i.Urutan,
		&i.RegNoCamat,
		&i.RegNoLurah,
		&i.TanggalRegCamat,
		&i.TanggalRegLurah,
		&i.TanggalSurat,
		&i.TempatTinggalPewaris,
		&i.PenerimaKuasaAhliWarisID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKuasaItem = `-- name: CreateKuasaItem :one
INSERT INTO kuasa_item (berkas_id, urutan, deskripsi)
VALUES (?, ?, ?)
RETURNING id, berkas_id, urutan, deskripsi
`

type CreateKuasaItemParams struct {
	BerkasID  int64  `json:"berkas_id"`
	Urutan    int64  `json:"urutan"`
	Deskripsi string `json:"deskripsi"`
}

// KUASA ITEM (editable)
func (q *Queries) CreateKuasaItem(ctx context.Context, arg CreateKuasaItemParams) (KuasaItem, error) {
	row := q.db.QueryRowContext(ctx, createKuasaItem, arg.BerkasID, arg.Urutan, arg.Deskripsi)
	var i KuasaItem
	err := row.Scan(
		&i.ID,
		&i.BerkasID,
		&i.Urutan,
		&i.Deskripsi,
	)
	return i, err
}

const createPejabat = `-- name: CreatePejabat :one
INSERT INTO pejabat (jabatan, nama, nip, aktif)
VALUES (?, ?, ?, ?)
RETURNING id, jabatan, nama, nip, aktif, created_at
`

type CreatePejabatParams struct {
	Jabatan string `json:"jabatan"`
	Nama    string `json:"nama"`
	Nip     string `json:"nip"`
	Aktif   int64  `json:"aktif"`
}

func (q *Queries) CreatePejabat(ctx context.Context, arg CreatePejabatParams) (Pejabat, error) {
	row := q.db.QueryRowContext(ctx, createPejabat,
		arg.Jabatan,
		arg.Nama,
		arg.Nip,
		arg.Aktif,
	)
	var i Pejabat
	err := row.Scan(
		&i.ID,
		&i.Jabatan,
		&i.Nama,
		&i.Nip,
		&i.Aktif,
		&i.CreatedAt,
	)
	return i, err
}

const createPewaris = `-- name: CreatePewaris :one
INSERT INTO pewaris (berkas_id, urutan, nama, nik, status, tgl_meninggal, instansi_kematian, no_surat_kematian, tgl_surat_kematian)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, berkas_id, urutan, nama, nik, status, tgl_meninggal, instansi_kematian, no_surat_kematian, tgl_surat_kematian
`

type CreatePewarisParams struct {
	BerkasID         int64  `json:"berkas_id"`
	Urutan           int64  `json:"urutan"`
	Nama             string `json:"nama"`
	Nik              string `json:"nik"`
	Status           string `json:"status"`
	TglMeninggal     string `json:"tgl_meninggal"`
	InstansiKematian string `json:"instansi_kematian"`
	NoSuratKematian  string `json:"no_surat_kematian"`
	TglSuratKematian string `json:"tgl_surat_kematian"`
}

func (q *Queries) CreatePewaris(ctx context.Context, arg CreatePewarisParams) (Pewaris, error) {
	row := q.db.QueryRowContext(ctx, createPewaris,
		arg.BerkasID,
		arg.Urutan,
		arg.Nama,
		arg.Nik,
		arg.Status,
		arg.TglMeninggal,
		arg.InstansiKematian,
		arg.NoSuratKematian,
		arg.TglSuratKematian,
	)
	var i Pewaris
	err := row.Scan(
		&i.ID,
		&i.BerkasID,
		&i.Urutan,
		&i.Nama,
		&i.Nik,
		&i.Status,
		&i.TglMeninggal,
		&i.InstansiKematian,
		&i.NoSuratKematian,
		&i.TglSuratKematian,
	)
	return i, err
}

const createSaksi = `-- name: CreateSaksi :exec
INSERT INTO saksi (berkas_id, urutan, nama, tempat_lahir, tgl_lahir, alamat, nik, hubungan)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSaksiParams struct {
	BerkasID    int64          `json:"berkas_id"`
	Urutan      int64          `json:"urutan"`
	Nama        string         `json:"nama"`
	TempatLahir sql.NullString `json:"tempat_lahir"`
	TglLahir    sql.NullString `json:"tgl_lahir"`
	Alamat      sql.NullString `json:"alamat"`
	Nik         sql.NullString `json:"nik"`
	Hubungan    sql.NullString `json:"hubungan"`
}

// SAKSI
func (q *Queries) CreateSaksi(ctx context.Context, arg CreateSaksiParams) error {
	_, err := q.db.ExecContext(ctx, createSaksi,
		arg.BerkasID,
		arg.Urutan,
		arg.Nama,
		arg.TempatLahir,
		arg.TglLahir,
		arg.Alamat,
		arg.Nik,
		arg.Hubungan,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, nama, role, must_change_password)
VALUES (?, ?, ?, ?, ?)
RETURNING id, username, password_hash, nama, role, must_change_password, created_at
`

type CreateUserParams struct {
	Username           string `json:"username"`
	PasswordHash       string `json:"password_hash"`
	Nama               string `json:"nama"`
	Role               string `json:"role"`
	MustChangePassword int64  `json:"must_change_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Nama,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nama,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const deactivatePejabatByJabatan = `-- name: DeactivatePejabatByJabatan :exec
UPDATE pejabat SET aktif = 0 WHERE jabatan = ?
`

func (q *Queries) DeactivatePejabatByJabatan(ctx context.Context, jabatan string) error {
	_, err := q.db.ExecContext(ctx, deactivatePejabatByJabatan, jabatan)
	return err
}

const deleteKuasaItem = `-- name: DeleteKuasaItem :exec
DELETE FROM kuasa_item WHERE id = ?
`

func (q *Queries) DeleteKuasaItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKuasaItem, id)
	return err
}

const deleteNomorAwal = `-- name: DeleteNomorAwal :exec
DELETE FROM nomor_awal WHERE tahun = ?
`

func (q *Queries) DeleteNomorAwal(ctx context.Context, tahun int64) error {
	_, err := q.db.ExecContext(ctx, deleteNomorAwal, tahun)
	return err
}

const deletePejabat = `-- name: DeletePejabat :exec
DELETE FROM pejabat WHERE id = ?
`

func (q *Queries) DeletePejabat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePejabat, id)
	return err
}

const ensurePengaturanRow = `-- name: EnsurePengaturanRow :exec
INSERT OR IGNORE INTO pengaturan (id) VALUES (1)
`

func (q *Queries) EnsurePengaturanRow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensurePengaturanRow)
	return err
}

const getAhliWaris = `-- name: GetAhliWaris :one
SELECT id, berkas_id, urutan, nama, nik, umur, jenis_kelamin, agama, alamat, keterangan, tempat_lahir, tgl_lahir, pekerjaan
FROM ahli_waris
WHERE id = ?
`

func (q *Queries) GetAhliWaris(ctx context.Context, id int64) (AhliWaris, error) {
	row := q.db.QueryRowContext(ctx, getAhliWaris, id)
	var i AhliWaris
	err := row.Scan(
		&i.ID,
		&i.BerkasID,
		&i.Urutan,
		&i.Nama,
		&i.Nik,
		&i.Umur,
		&i.JenisKelamin,
		&i.Agama,
		&i.Alamat,
		&i.Keterangan,
		&i.TempatLahir,
		&i.TglLahir,
		&i.Pekerjaan,
	)
	return i, err
}

const getBerkas = `-- name: GetBerkas :one
SELECT id, tahun, urutan, reg_no_camat, reg_no_lurah, tanggal_reg_camat, tanggal_reg_lurah,
       tanggal_surat, tempat_tinggal_pewaris, penerima_kuasa_ahli_waris_id, status,
       created_by, created_at, updated_at
FROM berkas_waris
WHERE id = ?
`

func (q *Queries) GetBerkas(ctx context.Context, id int64) (BerkasWaris, error) {
	row := q.db.QueryRowContext(ctx, getBerkas, id)
	var i BerkasWaris
	err := row.Scan(
		&i.ID,
		&i.Tahun,
		&i.Urutan,
		&i.RegNoCamat,
		&i.RegNoLurah,
		&i.TanggalRegCamat,
		&i.TanggalRegLurah,
		&i.TanggalSurat,
		&i.TempatTinggalPewaris,
		&i.PenerimaKuasaAhliWarisID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKuasaItem = `-- name: GetKuasaItem :one
SELECT id, berkas_id, urutan, deskripsi FROM kuasa_item WHERE id = ?
`

func (q *Queries) GetKuasaItem(ctx context.Context, id int64) (KuasaItem, error) {
	row := q.db.QueryRowContext(ctx, getKuasaItem, id)
	var i KuasaItem
	err := row.Scan(
		&i.ID,
		&i.BerkasID,
		&i.Urutan,
		&i.Deskripsi,
	)
	return i, err
}

const getNomorAwal = `-- name: GetNomorAwal :one
SELECT urutan_awal FROM nomor_awal WHERE tahun = ?
`

func (q *Queries) GetNomorAwal(ctx context.Context, tahun int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNomorAwal, tahun)
	var urutan_awal int64
	err := row.Scan(&urutan_awal)
	return urutan_awal, err
}

const getPejabat = `-- name: GetPejabat :one
SELECT id, jabatan, nama, nip, aktif, created_at
FROM pejabat
WHERE id = ?
`

func (q *Queries) GetPejabat(ctx context.Context, id int64) (Pejabat, error) {
	row := q.db.QueryRowContext(ctx, getPejabat, id)
	var i Pejabat
	err := row.Scan(
		&i.ID,
		&i.Jabatan,
		&i.Nama,
		&i.Nip,
		&i.Aktif,
		&i.CreatedAt,
	)
	return i, err
}

const getPejabatAktif = `-- name: GetPejabatAktif :one
SELECT id, jabatan, nama, nip, aktif, created_at
FROM pejabat
WHERE jabatan = ? AND aktif = 1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPejabatAktif(ctx context.Context, jabatan string) (Pejabat, error) {
	row := q.db.QueryRowContext(ctx, getPejabatAktif, jabatan)
	var i Pejabat
	err := row.Scan(
		&i.ID,
		&i.Jabatan,
		&i.Nama,
		&i.Nip,
		&i.Aktif,
		&i.CreatedAt,
	)
	return i, err
}

const getPengaturan = `-- name: GetPengaturan :one

SELECT id, nama_kelurahan, kecamatan, kota, kode_kecamatan, kode_kelurahan, instansi_kematian
FROM pengaturan
WHERE id = 1
`

// ============================================================
// PENGATURAN (satu baris, id = 1)
// ============================================================
func (q *Queries) GetPengaturan(ctx context.Context) (Pengaturan, error) {
	row := q.db.QueryRowContext(ctx, getPengaturan)
	var i Pengaturan
	err := row.Scan(
		&i.ID,
		&i.NamaKelurahan,
		&i.Kecamatan,
		&i.Kota,
		&i.KodeKecamatan,
		&i.KodeKelurahan,
		&i.InstansiKematian,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, nama, role, must_change_password, created_at
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nama,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one

SELECT id, username, password_hash, nama, role, must_change_password, created_at
FROM users
WHERE username = ?
`

// ============================================================
// USERS
// ============================================================
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nama,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const listAhliWarisByBerkas = `-- name: ListAhliWarisByBerkas :many
SELECT id, berkas_id, urutan, nama, nik, umur, jenis_kelamin, agama, alamat, keterangan, tempat_lahir, tgl_lahir, pekerjaan
FROM ahli_waris
WHERE berkas_id = ?
ORDER BY urutan, id
`

func (q *Queries) ListAhliWarisByBerkas(ctx context.Context, berkasID int64) ([]AhliWaris, error) {
	rows, err := q.db.QueryContext(ctx, listAhliWarisByBerkas, berkasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AhliWaris{}
	for rows.Next() {
		var i AhliWaris
		if err := rows.Scan(
			&i.ID,
			&i.BerkasID,
			&i.Urutan,
			&i.Nama,
			&i.Nik,
			&i.Umur,
			&i.JenisKelamin,
			&i.Agama,
			&i.Alamat,
			&i.Keterangan,
			&i.TempatLahir,
			&i.TglLahir,
			&i.Pekerjaan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBerkas = `-- name: ListBerkas :many
SELECT id, tahun, urutan, reg_no_camat, reg_no_lurah, tanggal_reg_camat, tanggal_reg_lurah,
       tanggal_surat, tempat_tinggal_pewaris, penerima_kuasa_ahli_waris_id, status,
       created_by, created_at, updated_at
FROM berkas_waris
ORDER BY created_at DESC
`

func (q *Queries) ListBerkas(ctx context.Context) ([]BerkasWaris, error) {
	rows, err := q.db.QueryContext(ctx, listBerkas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BerkasWaris{}
	for rows.Next() {
		var i BerkasWaris
		if err := rows.Scan(
			&i.ID,
			&i.Tahun,
			&i.Urutan,
			&i.RegNoCamat,
			&i.RegNoLurah,
			&i.TanggalRegCamat,
			&i.TanggalRegLurah,
			&i.TanggalSurat,
			&i.TempatTinggalPewaris,
			&i.PenerimaKuasaAhliWarisID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKuasaItemByBerkas = `-- name: ListKuasaItemByBerkas :many
SELECT id, berkas_id, urutan, deskripsi
FROM kuasa_item
WHERE berkas_id = ?
ORDER BY urutan, id
`

func (q *Queries) ListKuasaItemByBerkas(ctx context.Context, berkasID int64) ([]KuasaItem, error) {
	rows, err := q.db.QueryContext(ctx, listKuasaItemByBerkas, berkasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KuasaItem{}
	for rows.Next() {
		var i KuasaItem
		if err := rows.Scan(
			&i.ID,
			&i.BerkasID,
			&i.Urutan,
			&i.Deskripsi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNomorAwal = `-- name: ListNomorAwal :many
SELECT tahun, urutan_awal FROM nomor_awal ORDER BY tahun DESC
`

func (q *Queries) ListNomorAwal(ctx context.Context) ([]NomorAwal, error) {
	rows, err := q.db.QueryContext(ctx, listNomorAwal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NomorAwal{}
	for rows.Next() {
		var i NomorAwal
		if err := rows.Scan(&i.Tahun, &i.UrutanAwal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPejabat = `-- name: ListPejabat :many

SELECT id, jabatan, nama, nip, aktif, created_at
FROM pejabat
ORDER BY jabatan, aktif DESC, created_at DESC
`

// ============================================================
// PEJABAT (Lurah / Camat)
// ============================================================
func (q *Queries) ListPejabat(ctx context.Context) ([]Pejabat, error) {
	rows, err := q.db.QueryContext(ctx, listPejabat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pejabat{}
	for rows.Next() {
		var i Pejabat
		if err := rows.Scan(
			&i.ID,
			&i.Jabatan,
			&i.Nama,
			&i.Nip,
			&i.Aktif,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPewarisByBerkas = `-- name: ListPewarisByBerkas :many
SELECT id, berkas_id, urutan, nama, nik, status, tgl_meninggal, instansi_kematian, no_surat_kematian, tgl_surat_kematian
FROM pewaris
WHERE berkas_id = ?
ORDER BY urutan, id
`

func (q *Queries) ListPewarisByBerkas(ctx context.Context, berkasID int64) ([]Pewaris, error) {
	rows, err := q.db.QueryContext(ctx, listPewarisByBerkas, berkasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pewaris{}
	for rows.Next() {
		var i Pewaris
		if err := rows.Scan(
			&i.ID,
			&i.BerkasID,
			&i.Urutan,
			&i.Nama,
			&i.Nik,
			&i.Status,
			&i.TglMeninggal,
			&i.InstansiKematian,
			&i.NoSuratKematian,
			&i.TglSuratKematian,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaksiByBerkas = `-- name: ListSaksiByBerkas :many
SELECT id, berkas_id, urutan, nama, tempat_lahir, tgl_lahir, alamat, nik, hubungan
FROM saksi
WHERE berkas_id = ?
ORDER BY urutan, id
`

func (q *Queries) ListSaksiByBerkas(ctx context.Context, berkasID int64) ([]Saksi, error) {
	rows, err := q.db.QueryContext(ctx, listSaksiByBerkas, berkasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Saksi{}
	for rows.Next() {
		var i Saksi
		if err := rows.Scan(
			&i.ID,
			&i.BerkasID,
			&i.Urutan,
			&i.Nama,
			&i.TempatLahir,
			&i.TglLahir,
			&i.Alamat,
			&i.Nik,
			&i.Hubungan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextUrutan = `-- name: NextUrutan :one

SELECT COALESCE(MAX(urutan), 0) + 1 AS next_urutan
FROM berkas_waris
WHERE tahun = ?
`

// ============================================================
// BERKAS WARIS + anak-anaknya
// ============================================================
func (q *Queries) NextUrutan(ctx context.Context, tahun int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextUrutan, tahun)
	var next_urutan int64
	err := row.Scan(&next_urutan)
	return next_urutan, err
}

const searchBerkas = `-- name: SearchBerkas :many
SELECT b.id, b.tahun, b.urutan, b.reg_no_camat, b.reg_no_lurah, b.tanggal_reg_camat, b.tanggal_reg_lurah,
       b.tanggal_surat, b.tempat_tinggal_pewaris, b.penerima_kuasa_ahli_waris_id, b.status,
       b.created_by, b.created_at, b.updated_at
FROM berkas_waris b
WHERE EXISTS (
    SELECT 1 FROM pewaris p
    WHERE p.berkas_id = b.id
      AND (p.nama LIKE '%' || ?1 || '%' OR p.nik LIKE '%' || ?1 || '%')
)
OR b.reg_no_camat LIKE '%' || ?1 || '%'
OR b.reg_no_lurah LIKE '%' || ?1 || '%'
ORDER BY b.created_at DESC
`

func (q *Queries) SearchBerkas(ctx context.Context, dollar_1 sql.NullString) ([]BerkasWaris, error) {
	rows, err := q.db.QueryContext(ctx, searchBerkas, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BerkasWaris{}
	for rows.Next() {
		var i BerkasWaris
		if err := rows.Scan(
			&i.ID,
			&i.Tahun,
			&i.Urutan,
			&i.RegNoCamat,
			&i.RegNoLurah,
			&i.TanggalRegCamat,
			&i.TanggalRegLurah,
			&i.TanggalSurat,
			&i.TempatTinggalPewaris,
			&i.PenerimaKuasaAhliWarisID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBerkasPenerimaKuasa = `-- name: SetBerkasPenerimaKuasa :exec
UPDATE berkas_waris
SET penerima_kuasa_ahli_waris_id = ?, updated_at = datetime('now')
WHERE id = ?
`

type SetBerkasPenerimaKuasaParams struct {
	PenerimaKuasaAhliWarisID sql.NullInt64 `json:"penerima_kuasa_ahli_waris_id"`
	ID                       int64         `json:"id"`
}

func (q *Queries) SetBerkasPenerimaKuasa(ctx context.Context, arg SetBerkasPenerimaKuasaParams) error {
	_, err := q.db.ExecContext(ctx, setBerkasPenerimaKuasa, arg.PenerimaKuasaAhliWarisID, arg.ID)
	return err
}

const touchBerkas = `-- name: TouchBerkas :exec
UPDATE berkas_waris SET updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) TouchBerkas(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchBerkas, id)
	return err
}

const updateAhliWarisPelengkap = `-- name: UpdateAhliWarisPelengkap :exec
UPDATE ahli_waris
SET tempat_lahir = ?, tgl_lahir = ?, pekerjaan = ?
WHERE id = ? AND berkas_id = ?
`

type UpdateAhliWarisPelengkapParams struct {
	TempatLahir sql.NullString `json:"tempat_lahir"`
	TglLahir    sql.NullString `json:"tgl_lahir"`
	Pekerjaan   sql.NullString `json:"pekerjaan"`
	ID          int64          `json:"id"`
	BerkasID    int64          `json:"berkas_id"`
}

func (q *Queries) UpdateAhliWarisPelengkap(ctx context.Context, arg UpdateAhliWarisPelengkapParams) error {
	_, err := q.db.ExecContext(ctx, updateAhliWarisPelengkap,
		arg.TempatLahir,
		arg.TglLahir,
		arg.Pekerjaan,
		arg.ID,
		arg.BerkasID,
	)
	return err
}

const updateKuasaItem = `-- name: UpdateKuasaItem :exec
UPDATE kuasa_item SET deskripsi = ? WHERE id = ?
`

type UpdateKuasaItemParams struct {
	Deskripsi string `json:"deskripsi"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateKuasaItem(ctx context.Context, arg UpdateKuasaItemParams) error {
	_, err := q.db.ExecContext(ctx, updateKuasaItem, arg.Deskripsi, arg.ID)
	return err
}

const updatePejabat = `-- name: UpdatePejabat :exec
UPDATE pejabat
SET jabatan = ?, nama = ?, nip = ?, aktif = ?
WHERE id = ?
`

type UpdatePejabatParams struct {
	Jabatan string `json:"jabatan"`
	Nama    string `json:"nama"`
	Nip     string `json:"nip"`
	Aktif   int64  `json:"aktif"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdatePejabat(ctx context.Context, arg UpdatePejabatParams) error {
	_, err := q.db.ExecContext(ctx, updatePejabat,
		arg.Jabatan,
		arg.Nama,
		arg.Nip,
		arg.Aktif,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?, must_change_password = 0
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const upsertNomorAwal = `-- name: UpsertNomorAwal :exec
INSERT INTO nomor_awal (tahun, urutan_awal) VALUES (?, ?)
ON CONFLICT(tahun) DO UPDATE SET urutan_awal = excluded.urutan_awal
`

type UpsertNomorAwalParams struct {
	Tahun      int64 `json:"tahun"`
	UrutanAwal int64 `json:"urutan_awal"`
}

func (q *Queries) UpsertNomorAwal(ctx context.Context, arg UpsertNomorAwalParams) error {
	_, err := q.db.ExecContext(ctx, upsertNomorAwal, arg.Tahun, arg.UrutanAwal)
	return err
}

const upsertPengaturan = `-- name: UpsertPengaturan :exec
INSERT INTO pengaturan (id, nama_kelurahan, kecamatan, kota, kode_kecamatan, kode_kelurahan, instansi_kematian)
VALUES (1, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    nama_kelurahan    = excluded.nama_kelurahan,
    kecamatan         = excluded.kecamatan,
    kota              = excluded.kota,
    kode_kecamatan    = excluded.kode_kecamatan,
    kode_kelurahan    = excluded.kode_kelurahan,
    instansi_kematian = excluded.instansi_kematian
`

type UpsertPengaturanParams struct {
	NamaKelurahan    sql.NullString `json:"nama_kelurahan"`
	Kecamatan        sql.NullString `json:"kecamatan"`
	Kota             sql.NullString `json:"kota"`
	KodeKecamatan    sql.NullString `json:"kode_kecamatan"`
	KodeKelurahan    sql.NullString `json:"kode_kelurahan"`
	InstansiKematian sql.NullString `json:"instansi_kematian"`
}

func (q *Queries) UpsertPengaturan(ctx context.Context, arg UpsertPengaturanParams) error {
	_, err := q.db.ExecContext(ctx, upsertPengaturan,
		arg.NamaKelurahan,
		arg.Kecamatan,
		arg.Kota,
		arg.KodeKecamatan,
		arg.KodeKelurahan,
		arg.InstansiKematian,
	)
	return err
}
